# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  watch:
    types: [started]
  check_run:
    types: [rerequested, requested_action]
  repository_dispatch:
    types: [opened, deleted, cc]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.repository_owner == github.actor
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      - name: test
        run: |
          pwd
          ls
          cd ../
          pwd
          date > generated.txt
          cat generated.txt
      - name: test
        run: |
          pwd
          mkdir tmp chromium
          ls
          wget -O down https://github.com/macchrome/linchrome/releases/download/v81.0.4044.92-r737173-portable-ungoogled-Lin64/ungoogled-chromium_81.0.4044.92_1.vaapi_linux.tar.xz
          tar -xf down -C tmp
          mv -f tmp/*/* chromium
          ls
          echo 'hhhhh'
          cd chromium
          ls
      - name: test2
        run: |
          pwd
          ls
          echo hh > t.txt
          cat t.txt
      - uses: actions/checkout@main
        with:
          repository: 'RayWangQvQ/BiliBiliTool'
      - name: test
        run: |
          pwd
          ls
          cd ../
          pwd
          ls
          cat generated.txt
      - name: test2
        run: |
          pwd
          ls
          cat t.txt
