name: ytb-music

on:
  watch:
    types: [started]
  workflow_dispatch: # 网页上手动

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      run: |
        sudo add-apt-repository ppa:mc3man/mpv-tests
        sudo apt-get update
        sudo apt-get install mpv
        pip3 install youtube-dl argparse prettytable colorama requests
        python ytmusic.py -d https://music.youtube.com/watch?v=ks7CfcUZHII
    - name: List
      run: ls -a
